language: python
python:
- 2.7
- 3.5
- 3.6
env:
- DJANGO="Django>=1.11,<1.12"
install:
- pip install -q $DJANGO django-appconf coveralls
script:
- coverage run -a --source=axes runtests.py
- coverage report
after_success:
- coveralls
